apiVersion: v1
kind: Service
metadata:
  name: ${{values.component_id}}
  labels:
    {{- include "quarkus-template.labels" . | nindent 4 }}
  namespace: dev-hub-test
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quarkus-template.selectorLabels" . | nindent 4 }}
