{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quarkus-template.serviceAccountName" . }}
  namespace: dev-hub-test
  labels:
    {{- include "quarkus-template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
imagePullSecrets:
  - name: registry-creds-app
